[package]
name = "symbolic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = "0.11.2"
env_logger = "0.6"
owning_ref = "0.4.1"
ouroboros = "0.15.0"
z3-sys = "0.7.1"
